apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: backend-deployment
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  
  template:
    metadata:
      
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: rishav23/chatapp-backend:latest
        name: chatapp-backend
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGO_DB_URL
          value: "mongodb://root:root@mongodb:27017/dbname?authSource=admin"
        - name: SECRET_TOKEN
          valueFrom:
             secretKeyRef:
                 name: chatapp-secrets
                 key: JWT
        - name: PORT
          value: "5001"
