apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db
  name: mongo-db
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-db
  
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-db
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_INIT_PASSWORD
          value: root
        - name: MONGODB_INIT_USERNAME
          value: root
        volumeMounts:
        - mountPath: /data
          name: mongodb-vol
      volumes:
        - name: mongodb-vol
          persistentVolumeClaim:
             claimName: mongodb-pvc

